baseURL = "https://yurai-kitadate.github.io/"
languageCode = "ja"
title = "Tk's blog"
theme = "github-style"
googleAnalytics = "UA-123456-789"
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  author = "Tk"
  description = "Hello there👋"
  github = "Yurai-Kitadate"
  twitter = "tk_onl"
  url = "https://yurai-kitadate.github.io/"
  rss = true
  lastmod = true
  userStatusEmoji = "😀"
  favicon = "/images/github.png"
  location = "Japan"
  enableGitalk = true

  [params.gitalk]
    clientID = "Your client ID"
    clientSecret = "Your client secret"
    repo = "repo"
    owner = "MeiK2333"
    admin = "MeiK2333"
    id = "location.pathname"
    labels = "gitalk"
    perPage = 15
    pagerDirection = "last"
    createIssueManually = true
    distractionFreeMode = false

  [[params.links]]
    title = "Link"
    href = "https://github.com/Yurai-Kitadate"
[frontmatter]
    lastmod = ["lastmod", ":fileModTime", ":default"]
